src/main/java/br/spaixaox/model/AtendimentoPaciente.java
package br.spaixaox.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.springframework.util.StringUtils;

import br.spaixaox.model.enums.StatusAtendimentoPaciente;
import br.spaixaox.model.enums.TipoAtendimentoPaciente;
import br.spaixaox.util.jsf.FacesUtil;

@Entity
@Table(name="atendimento_paciente")
public class AtendimentoPaciente implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "atendimento_paciente_id_seq")
	@SequenceGenerator(name = "atendimento_paciente_id_seq", sequenceName = "atendimento_paciente_id_seq", allocationSize = 1)	
	private Long id;
	
	@Column(nullable=true)
	private boolean prioritario = false;

	@Column(nullable = true, length = 50)
	private String resumo;//poucas palavras para aparecer no Histórico
	
	@NotNull
	@ManyToOne
	@JoinColumn(name = "animal_id", nullable = false, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__animal__animal_id"))	
	private Animal animal;

	@Column(nullable = true)
	private Double peso;
	
	//@NotNull
	@ManyToOne
	@JoinColumn(name = "veterinario_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__veterinario__veterinario_id"))	
	private Veterinario veterinario;

	//@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_criacao")	
	private Date dataCriacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_inicio")	
	private Date dataHoraInicio;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_fim")	
	private Date dataHoraFim;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_cancelamento")	
	private Date dataHoraCancelamento;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private StatusAtendimentoPaciente status = StatusAtendimentoPaciente.ESPERA;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name="tipo_atendimento_paciente", nullable = false, length = 20)
	private TipoAtendimentoPaciente tipoAtendimentoPaciente = TipoAtendimentoPaciente.CLINICO;	

	@Column(columnDefinition = "text")
	private String anamnese; 	

	@Column(columnDefinition = "text")
	private String diagnostico;

	@Column(name = "exame_complementar2",columnDefinition = "text")
	private String exameComplementar2;	
	
	@Column(name = "resultado_exame_complementar2",columnDefinition = "text")
	private String resultadoExameComplementar2;	
	
	@Column(columnDefinition = "text")
	private String tratamento;	
	
	@Column(name = "tratamento_cirurgico",columnDefinition = "text")
	private String tratamentoCirurgico;	
	
	@Column(name = "exame_fisico", columnDefinition = "text")
	private String exameFisico;	

	@Column(columnDefinition = "text")
	private String receituario;
	
	@Column(columnDefinition = "text")
	private String observacao;

	/*
	
	@ManyToOne
	@JoinColumn(name = "usuario_criou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_criou_id"))	
	private Usuario usuarioCriou;
	
	@ManyToOne
	@JoinColumn(name = "usuario_iniciou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_iniciou_id"))	
	private Usuario usuarioIniciou;

	@ManyToOne
	@JoinColumn(name = "usuario_finalizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_finalizou_id"))	
	private Usuario usuarioFinalizou;	

	@ManyToOne
	@JoinColumn(name = "usuario_atualizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_atualizou_id"))	
	private Usuario usuarioAtualizou;	
	
	@ManyToOne
	@JoinColumn(name = "patologia_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__patologia__patologia_id"))	
	private Patologia patologia;	
	
	@Column(name="outra_patologia", length = 100)
	private String outraPatologia;//patologia principal	

	//@NotNull
	@ManyToOne
	@JoinColumn(name = "consultorio_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__consultorio__consultorio_id"))	
	private Consultorio consultorio;		
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_criacao")	
	private Date dataHoraCriacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_atualizacao")	
	private Date dataHoraAtualizacao;
	*/
	
	@Transient
	public boolean isNovo(){
		return getId() == null;
	}

	@Transient	
	public boolean isExistente(){
		return !isNovo();
	}

	@Transient	
	public boolean isEmAtendimento(){
		return this.status == StatusAtendimentoPaciente.ATENDIMENTO;
	}
	
	@Transient	
	public boolean isEmEspera(){
		return this.status == StatusAtendimentoPaciente.ESPERA;
	}	
    
	@Transient	
	public boolean isFinalizado(){
		return this.status == StatusAtendimentoPaciente.ATENDIDO;
	}
    
	@Transient	
	public boolean isCancelado(){
		return this.status == StatusAtendimentoPaciente.CANCELADO;
	}
	
	@Transient
	public String getNomePrioritario(){
		return this.prioritario ? "Prioritário" : "";
	}

	@Transient	
	public boolean isTipoAtendimentoCirurgico(){
		return this.tipoAtendimentoPaciente == TipoAtendimentoPaciente.CIRURGICO;
	}

	@Transient	
	public boolean isTipoAtendimentoExameLaudo(){
		return this.tipoAtendimentoPaciente == TipoAtendimentoPaciente.EXAME;
	}
	
	
	public boolean isPrioritario() {
		return prioritario;
	}

	public void setPrioritario(boolean prioritario) {
		this.prioritario = prioritario;
	}

	public String getResumo() {
		return resumo;
	}

	public void setResumo(String resumo) {
		this.resumo = resumo;
	}

	public Animal getAnimal() {
		return animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	public Double getPeso() {
		return peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Veterinario getVeterinario() {
		return veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataHoraInicio() {
		return dataHoraInicio;
	}

	public void setDataHoraInicio(Date dataHoraInicio) {
		this.dataHoraInicio = dataHoraInicio;
	}

	public Date getDataHoraFim() {
		return dataHoraFim;
	}

	public void setDataHoraFim(Date dataHoraFim) {
		this.dataHoraFim = dataHoraFim;
	}

	public Date getDataHoraCancelamento() {
		return dataHoraCancelamento;
	}

	public void setDataHoraCancelamento(Date dataHoraCancelamento) {
		this.dataHoraCancelamento = dataHoraCancelamento;
	}

	public StatusAtendimentoPaciente getStatus() {
		return status;
	}

	public void setStatus(StatusAtendimentoPaciente status) {
		this.status = status;
	}

	public TipoAtendimentoPaciente getTipoAtendimentoPaciente() {
		return tipoAtendimentoPaciente;
	}

	public void setTipoAtendimentoPaciente(
			TipoAtendimentoPaciente tipoAtendimentoPaciente) {
		this.tipoAtendimentoPaciente = tipoAtendimentoPaciente;
	}

	public String getAnamnese() {
		return anamnese;
	}

	public void setAnamnese(String anamnese) {
		this.anamnese = anamnese;
	}

	public String getDiagnostico() {
		return diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	public String getExameComplementar2() {
		return exameComplementar2;
	}

	public void setExameComplementar2(String exameComplementar2) {
		this.exameComplementar2 = exameComplementar2;
	}

	public String getResultadoExameComplementar2() {
		return resultadoExameComplementar2;
	}

	public void setResultadoExameComplementar2(String resultadoExameComplementar2) {
		this.resultadoExameComplementar2 = resultadoExameComplementar2;
	}

	public String getTratamento() {
		return tratamento;
	}

	public void setTratamento(String tratamento) {
		this.tratamento = tratamento;
	}

	public String getTratamentoCirurgico() {
		return tratamentoCirurgico;
	}

	public void setTratamentoCirurgico(String tratamentoCirurgico) {
		this.tratamentoCirurgico = tratamentoCirurgico;
	}

	public String getExameFisico() {
		return exameFisico;
	}

	public void setExameFisico(String exameFisico) {
		this.exameFisico = exameFisico;
	}

	public String getReceituario() {
		return receituario;
	}

	public void setReceituario(String receituario) {
		this.receituario = receituario;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public Long getId() {
		return id;
	}
	
	@Transient	
	public boolean isPodeIniciar(){
	  boolean pode = true;
	  
		if (this.animal == null ) {
			pode = false;
			FacesUtil.addErrorMessage("O animal deve ser informado.");
		} else {
            if (this.veterinario == null){
				pode = false;
				FacesUtil.addErrorMessage("O Dr(a). veterinário(a) deve ser informado(a).");
            }
		}

		return pode;
	}
	
	
	@Transient	
	public boolean isPodeFinalizar(){
	  boolean pode = true;
	  
		if (this.getDataHoraInicio() == null) {
			pode = false;
			FacesUtil.addErrorMessage("O atendimento deve ser inicializado.");
		} else {
			if (this.animal == null ) {
				pode = false;
				FacesUtil.addErrorMessage("O animal deve ser informado informado.");
			} else {
                if (this.veterinario == null){
					pode = false;
					FacesUtil.addErrorMessage("O Dr(a). veterinário(a) deve ser informado(a).");
                } else {

src/main/webapp/WEB-INF/template/atendimentospacientes/ArquivosAtendimentoPacientes.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui">    
	
			<p:growl showDetail="true" autoUpdate="true" />

			<h:panelGrid columns="3">

				<h:inputText id="descricao" size="30" maxlength="50"
				   value="#{cadastroAtendimentoPacienteBean.uploadArquivo.descricao}" 
				   pt:placeholder="Descrição do Arquivo">
			       <p:ajax event="blur" />   
				</h:inputText>   
			    
				<p:outputLabel value="Anexar Arquivos: " for="fileUpload"/>
				<p:fileUpload id="fileUpload"	
					fileUploadListener="#{cadastroAtendimentoPacienteBean.upload}"
					process="descricao" update="arquivosTable descricao" 
	                allowTypes="/(\.|\/)(gif|jpe?g|png|pdf)$/"
		            invalidFileMessage="São permitidas somente imagens e pdf (gif, jpeg, pdf, jpg, png e pdf)"
		            
	                sizeLimit="5242880" 
		            invalidSizeMessage="O tamanho máximo permitido é de 5MB."
		            fileLimit="5" 
		            fileLimitMessage="Só é possível escolher 5 arquivos por vez." 
		            skinSimple="true" 
		            multiple="false"
		            auto="false"
		            dragDropSupport="true"
		            sequential="true"
		            
		            onstart="console.log('Iniciando envio de arquivo')"
		            onerror="console.log('Erro na requisição de envio')"
		            oncomplete="console.log('Envio concluído')"
		             
				    label="Escolher" uploadLabel="Enviar" cancelLabel="Cancelar"  />

			</h:panelGrid>

			<p:spacer height="20px" />

               
    <h:panelGroup layout="block" style="padding-right: 10px">
	    	<p:dataTable id="arquivosTable" value="#{cadastroAtendimentoPacienteBean.uploadArquivos}" var="arquivo"
		    		style="margin-top: 20px" emptyMessage="Nenhum arquivo anexado a este atendimento."
		    		rows="5" paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom">
		    

				<p:column headerText="Ação" style="text-align: center; width: 50px">
				<p:outputLabel value="Arquivo inexistente" rendered="#{cadastroAtendimentoPacienteBean.naoExisteArquivo(arquivo.caminhoDiretorio, arquivo.nomeDestino)}"/>
				
					<p:commandButton value="Baixar" ajax="false" rendered="#{cadastroAtendimentoPacienteBean.existeArquivo(arquivo.caminhoDiretorio, arquivo.nomeDestino)}"
						actionListener="#{uploadAvancadoBean.download(arquivo.caminhoDiretorio, arquivo.nomeDestino)}"
						icon="ui-icon-arrowthick-1-s">
						<p:fileDownload value="#{uploadAvancadoBean.streamedContent}" />
					</p:commandButton>
				</p:column>


				<p:column headerText="Data Upload" style="text-align: center; width: 80px">
				   <h:outputFormat  id="data" value="#{arquivo.dataHoraUpload}">
				      <f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
				   </h:outputFormat>
				</p:column>

	    		<p:column headerText="Atend." style="text-align: center; width: 30px"
	    		rendered="false">
	    			<h:outputText value="#{arquivo.atendimentoPaciente.id}"/>
	    		</p:column>

	    		<p:column headerText="ContentType" style="text-align: center; width: 100px">
	    			<h:outputText value="#{arquivo.contentType}"/>
	    		</p:column>

	    		<p:column headerText="Descrição" style="text-align: center; width: 100px">
	    			<h:outputText value="#{arquivo.descricao}"/>
	    		</p:column>

	    		<p:column headerText="Módulo" style="text-align: center; width: 70px">
	    			<h:outputText value="#{arquivo.moduloSistema}"/>
	    		</p:column>	    		

	    		<p:column headerText="Diretório" style="text-align: center; width: 100px">
	    			<h:outputText value="#{arquivo.caminhoDiretorio}"/>
	    		</p:column>

	    		<p:column headerText="Nome Original" style="text-align: center; width: 100px">
	    			<h:outputText value="#{arquivo.nomeOrigem}"/>
	    		</p:column>

	    		<p:column headerText="Nome Atual" style="text-align: center; width: 100px">
	    			<h:outputText value="#{arquivo.nomeDestino}"/>
	    		</p:column>
	    		
	    	</p:dataTable>
	</h:panelGroup>	
    
</ui:composition>

src/main/webapp/WEB-INF/template/atendimentospacientes/BotoesAtendimentoPacientes.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
		<p:toolbarGroup>
			<p:commandButton value="Salvar"
				action="#{cadastroAtendimentoPacienteBean.salvar}" 
				update="frmCadastro" disabled="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.cancelado}" />
			<p:separator />  
			<p:commandButton value="Iniciar" 
				action="#{cadastroAtendimentoPacienteBean.iniciarAtendimento}" 
				update="frmCadastro" disabled="#{!cadastroAtendimentoPacienteBean.atendimentoPaciente.emEspera}"/>
            
			<p:commandButton value="Finalizar" 
				action="#{cadastroAtendimentoPacienteBean.finalizarAtendimento}" 
				update="frmCadastro" disabled="#{!cadastroAtendimentoPacienteBean.atendimentoPaciente.emAtendimento}"/>
		</p:toolbarGroup>
		
		<p:toolbarGroup align="right">
			<p:commandButton value="Cancelar" 
				action="#{cadastroAtendimentoPacienteBean.cancelarAtendimento}" 
				update="frmCadastro" disabled="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.cancelado}"/>
			<p:separator />

			<p:button value="Pesquisar"
			       outcome="PesquisaAtendimentoPacientes"/>

		</p:toolbarGroup>
	</p:toolbar>

</ui:composition>

src/main/webapp/WEB-INF/template/atendimentospacientes/CorpoAtendimentoPacientes.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="6" style="width: 100%; margin-top: 20px" 
		columnClasses="rotulo, campo, rotulo, campo">
		
		<p:outputLabel value="Atendimento" />
		<h:outputText id="numeroAtendimento" size="5" maxlength="5" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.id}" >
		</h:outputText>

		<p:outputLabel value="Prioritário" />
        <p:selectBooleanCheckbox itemLabel=""
			value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.prioritario}">
  	    </p:selectBooleanCheckbox>

		<p:outputLabel value="Resumo" />
		<h:inputText id="resumo" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.resumo}" >
		</h:inputText>

		<h:outputLabel value="Status" />
		<p:selectOneMenu id="status" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.status}" disabled="true">
		  <f:selectItem itemLabel="Selecione um status" />		
		  <f:selectItems value="#{cadastroAtendimentoPacienteBean.statusAtendimentoPaciente}" var="status"
			   itemValue="#{status}" itemLabel="#{status.descricao}"/>
		</p:selectOneMenu>        
        
		<h:outputLabel value="Tipo Atendimento" />
		<p:selectOneMenu id="tipoAtendimentoPaciente" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.tipoAtendimentoPaciente}">
		  <f:selectItem itemLabel="Selecione um tipo de atendimento" />		
		  <f:selectItems value="#{cadastroAtendimentoPacienteBean.tipoAtendimentoPaciente}" var="tipoAtendimentoPaciente"
			   itemValue="#{tipoAtendimentoPaciente}" itemLabel="#{tipoAtendimentoPaciente.descricao}"/>
		</p:selectOneMenu>        

		<p:outputLabel value="Cod. Animal" for="codAnimal" />
		<h:outputText id="codAnimal" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal.id}" >
		</h:outputText>
        
		<p:outputLabel value="Animal" for="animal" />
		<h:outputText id="animal" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal.nome}" >
		</h:outputText>

		<p:outputLabel value="Espécie" for="especie" />
		<h:outputText id="especie" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal.especie.nome}" >
		</h:outputText>

		<p:outputLabel value="Raça" for="raca" />
		<h:outputText id="raca" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal.raca.nome}" >
		</h:outputText>

     	<p:outputLabel value="Proprietário" for="proprietario" />
		<h:outputText id="proprietario" size="30" maxlength="50" 
		   value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal.proprietario.nome}" >
		</h:outputText>

		<p:outputLabel value="Dr. Veterinário" for="veterinario" />		
		<p:selectOneMenu id="veterinario" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.veterinario}">
			<f:selectItem itemLabel="Selecione um Dr. veterinário" />
			<f:selectItems value="#{cadastroAtendimentoPacienteBean.veterinarios}" var="veterinario" 
			   itemValue="#{veterinario}" itemLabel="#{veterinario.nome}"/>
		</p:selectOneMenu>		
		
		<p:outputLabel value="Pesagem" for="peso" />		
	    <p:inputText  type="number" id="peso" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.peso}" />

		<p:outputLabel value="Início" for="dataInicio" />		
	    <h:outputFormat  id="dataInicio" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.dataHoraInicio}">
	       <f:convertDateTime pattern="dd/MM/yyyy  HH:mm:ss" /> 
	    </h:outputFormat>

		<p:outputLabel value="Fim" for="dataHoraFim" />
	    <h:outputFormat  id="dataHoraFim" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.dataHoraFim}">
	      <f:convertDateTime pattern="dd/MM/yyyy  HH:mm:ss" />
	    </h:outputFormat>
	</p:panelGrid>

    <div style="margin-top:20px">	
	<p:panelGrid columns="1" style="width: 100%; margin-top: 20px"  
		columnClasses="rotulo, campo, rotulo, campo">

        <p:outputLabel value="***** Lembre-se de selecionar o seu Consultório e clicar no botão 'INICIAR' para começar o atendimento *****" style="margin-top:20px;background-color: #FF0000;color: #fff;font-size: 16px;" rendered="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.emEspera}" />
		<p:outputLabel value="Anamnese" style="margin-top:20px" for="anamnese"/>	 	
		<p:inputTextarea rows="20" style="width: 100%" 
		      id="anamnese" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.anamnese}" />

		<p:outputLabel value="Avaliação Física" style="margin-top:20px" for="avaliacaoFisica"/>	 	
		<p:inputTextarea id="avaliacaoFisica" rows="10" style="width: 100%" 
		      value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.exameFisico}" />

		<p:outputLabel value="Exames Complementares" style="margin-top:20px" for="examecomplementar"/>
		<p:inputTextarea rows="3" style="width: 100%" 
		      id="examecomplementar" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.exameComplementar2}" />

		<p:outputLabel value="Resultado Exames Complementares" style="margin-top:20px" for="resultadoexame"/>
		<p:inputTextarea rows="3" style="width: 100%" 
		      id="resultadoexame" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.resultadoExameComplementar2}" />

		<p:outputLabel value="Diagnóstico Provável, Diagnóstico Definitivo e Prognóstico" style="margin-top:20px" for="diagnostico"/>	 	
		<p:inputTextarea rows="5" style="width: 100%"
		      id="diagnostico" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.diagnostico}" />

		<p:outputLabel value="Tratamento Clínico" style="margin-top:20px" for="tratamentoClinico"/>
		<p:inputTextarea rows="5" style="width: 100%"
		      id="tratamentoClinico" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.tratamento}" />

	</p:panelGrid>
	 </div>	

</ui:composition>

src/main/webapp/WEB-INF/template/atendimentospacientes/ObservacaoAtendimentoPacientes.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%"
		      id="observacao" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.observacao}"/>
	</h:panelGroup>	
  	
</ui:composition>

src/main/webapp/WEB-INF/template/atendimentospacientes/ReceituarioAtendimentoPacientes.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">

		<p:editor id="editorWidget" 
			widgetVar="editorWidget" height="300" style="margin-bottom:10px"
			value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.receituario}" 
			rendered="#{!cadastroAtendimentoPacienteBean.atendimentoPaciente.emEspera}"/>
			
			<!-- 

		<h:panelGrid columns="2" style="margin-top: 10px">

		
		<p:commandButton value="Teste" 
		oncomplete="PF('editorWidget').editor.execCommand('inserthtml','texto hr/n b inserido');"   
		process="@this" />
    
    	<p:commandButton value="Limpar" type="button"
				onclick="PF('editorWidget').clear();" icon="ui-icon-close" />

			<p:commandButton value="Salvar" update="display"
				oncomplete="PF('dlg').show()" icon="ui-icon-disk" />


		</h:panelGrid>
           -->

<!-- 
		<p:dialog header="Content" widgetVar="dlg" showEffect="fade"
			hideEffect="fade">
			<h:outputText id="display" value="#{editorView.text}" escape="false" />
		</p:dialog>
 -->

	</h:panelGroup>

</ui:composition>