src/main/java/br/spaixaox/model/AtendimentoPaciente.java
package br.spaixaox.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.springframework.util.StringUtils;

import br.spaixaox.model.enums.StatusAtendimentoPaciente;
import br.spaixaox.model.enums.TipoAtendimentoPaciente;
import br.spaixaox.util.jsf.FacesUtil;

@Entity
@Table(name="atendimento_paciente")
public class AtendimentoPaciente implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "atendimento_paciente_id_seq")
	@SequenceGenerator(name = "atendimento_paciente_id_seq", sequenceName = "atendimento_paciente_id_seq", allocationSize = 1)	
	private Long id;
	
	@Column(nullable=true)
	private boolean prioritario = false;

	@Column(nullable = true, length = 50)
	private String resumo;//poucas palavras para aparecer no Histórico
	
	@NotNull
	@ManyToOne
	@JoinColumn(name = "animal_id", nullable = false, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__animal__animal_id"))	
	private Animal animal;

	@Column(nullable = true)
	private Double peso;
	
	//@NotNull
	@ManyToOne
	@JoinColumn(name = "veterinario_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__veterinario__veterinario_id"))	
	private Veterinario veterinario;

	//@NotNull
	@Temporal(TemporalType.DATE)
	@Column(name = "data_criacao")	
	private Date dataCriacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_inicio")	
	private Date dataHoraInicio;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_fim")	
	private Date dataHoraFim;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_cancelamento")	
	private Date dataHoraCancelamento;

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private StatusAtendimentoPaciente status = StatusAtendimentoPaciente.ESPERA;
	
	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name="tipo_atendimento_paciente", nullable = false, length = 20)
	private TipoAtendimentoPaciente tipoAtendimentoPaciente = TipoAtendimentoPaciente.CLINICO;	

	@Column(columnDefinition = "text")
	private String anamnese; 	

	@Column(columnDefinition = "text")
	private String diagnostico;

	@Column(name = "exame_complementar2",columnDefinition = "text")
	private String exameComplementar2;	
	
	@Column(name = "resultado_exame_complementar2",columnDefinition = "text")
	private String resultadoExameComplementar2;	
	
	@Column(columnDefinition = "text")
	private String tratamento;	
	
	@Column(name = "tratamento_cirurgico",columnDefinition = "text")
	private String tratamentoCirurgico;	
	
	@Column(name = "exame_fisico", columnDefinition = "text")
	private String exameFisico;	

	@Column(columnDefinition = "text")
	private String receituario;
	
	@Column(columnDefinition = "text")
	private String observacao;

	/*
	
	@ManyToOne
	@JoinColumn(name = "usuario_criou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_criou_id"))	
	private Usuario usuarioCriou;
	
	@ManyToOne
	@JoinColumn(name = "usuario_iniciou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_iniciou_id"))	
	private Usuario usuarioIniciou;

	@ManyToOne
	@JoinColumn(name = "usuario_finalizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_finalizou_id"))	
	private Usuario usuarioFinalizou;	

	@ManyToOne
	@JoinColumn(name = "usuario_atualizou_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__usuario__usuario_atualizou_id"))	
	private Usuario usuarioAtualizou;	
	
	@ManyToOne
	@JoinColumn(name = "patologia_id", foreignKey = @ForeignKey(name = "fk_atendimento_paciente__patologia__patologia_id"))	
	private Patologia patologia;	
	
	@Column(name="outra_patologia", length = 100)
	private String outraPatologia;//patologia principal	

	//@NotNull
	@ManyToOne
	@JoinColumn(name = "consultorio_id", nullable=true, foreignKey = @ForeignKey(name = "fk_atendimento_paciente__consultorio__consultorio_id"))	
	private Consultorio consultorio;		
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_criacao")	
	private Date dataHoraCriacao;
	
	//@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_atualizacao")	
	private Date dataHoraAtualizacao;
	*/
	
	@Transient
	public boolean isNovo(){
		return getId() == null;
	}

	@Transient	
	public boolean isExistente(){
		return !isNovo();
	}

	@Transient	
	public boolean isEmAtendimento(){
		return this.status == StatusAtendimentoPaciente.ATENDIMENTO;
	}
	
	@Transient	
	public boolean isEmEspera(){
		return this.status == StatusAtendimentoPaciente.ESPERA;
	}	
    
	@Transient	
	public boolean isFinalizado(){
		return this.status == StatusAtendimentoPaciente.ATENDIDO;
	}
    
	@Transient	
	public boolean isCancelado(){
		return this.status == StatusAtendimentoPaciente.CANCELADO;
	}
	
	@Transient
	public String getNomePrioritario(){
		return this.prioritario ? "Prioritário" : "";
	}

	@Transient	
	public boolean isTipoAtendimentoCirurgico(){
		return this.tipoAtendimentoPaciente == TipoAtendimentoPaciente.CIRURGICO;
	}

	@Transient	
	public boolean isTipoAtendimentoExameLaudo(){
		return this.tipoAtendimentoPaciente == TipoAtendimentoPaciente.EXAME;
	}
	
	
	public boolean isPrioritario() {
		return prioritario;
	}

	public void setPrioritario(boolean prioritario) {
		this.prioritario = prioritario;
	}

	public String getResumo() {
		return resumo;
	}

	public void setResumo(String resumo) {
		this.resumo = resumo;
	}

	public Animal getAnimal() {
		return animal;
	}

	public void setAnimal(Animal animal) {
		this.animal = animal;
	}

	public Double getPeso() {
		return peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Veterinario getVeterinario() {
		return veterinario;
	}

	public void setVeterinario(Veterinario veterinario) {
		this.veterinario = veterinario;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	public Date getDataHoraInicio() {
		return dataHoraInicio;
	}

	public void setDataHoraInicio(Date dataHoraInicio) {
		this.dataHoraInicio = dataHoraInicio;
	}

	public Date getDataHoraFim() {
		return dataHoraFim;
	}

	public void setDataHoraFim(Date dataHoraFim) {
		this.dataHoraFim = dataHoraFim;
	}

	public Date getDataHoraCancelamento() {
		return dataHoraCancelamento;
	}

	public void setDataHoraCancelamento(Date dataHoraCancelamento) {
		this.dataHoraCancelamento = dataHoraCancelamento;
	}

	public StatusAtendimentoPaciente getStatus() {
		return status;
	}

	public void setStatus(StatusAtendimentoPaciente status) {
		this.status = status;
	}

	public TipoAtendimentoPaciente getTipoAtendimentoPaciente() {
		return tipoAtendimentoPaciente;
	}

	public void setTipoAtendimentoPaciente(
			TipoAtendimentoPaciente tipoAtendimentoPaciente) {
		this.tipoAtendimentoPaciente = tipoAtendimentoPaciente;
	}

	public String getAnamnese() {
		return anamnese;
	}

	public void setAnamnese(String anamnese) {
		this.anamnese = anamnese;
	}

	public String getDiagnostico() {
		return diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	public String getExameComplementar2() {
		return exameComplementar2;
	}

	public void setExameComplementar2(String exameComplementar2) {
		this.exameComplementar2 = exameComplementar2;
	}

	public String getResultadoExameComplementar2() {
		return resultadoExameComplementar2;
	}

	public void setResultadoExameComplementar2(String resultadoExameComplementar2) {
		this.resultadoExameComplementar2 = resultadoExameComplementar2;
	}

	public String getTratamento() {
		return tratamento;
	}

	public void setTratamento(String tratamento) {
		this.tratamento = tratamento;
	}

	public String getTratamentoCirurgico() {
		return tratamentoCirurgico;
	}

	public void setTratamentoCirurgico(String tratamentoCirurgico) {
		this.tratamentoCirurgico = tratamentoCirurgico;
	}

	public String getExameFisico() {
		return exameFisico;
	}

	public void setExameFisico(String exameFisico) {
		this.exameFisico = exameFisico;
	}

	public String getReceituario() {
		return receituario;
	}

	public void setReceituario(String receituario) {
		this.receituario = receituario;
	}

	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public Long getId() {
		return id;
	}
	
	@Transient	
	public boolean isPodeIniciar(){
	  boolean pode = true;
	  
		if (this.animal == null ) {
			pode = false;
			FacesUtil.addErrorMessage("O animal deve ser informado.");
		} else {
            if (this.veterinario == null){
				pode = false;
				FacesUtil.addErrorMessage("O Dr(a). veterinário(a) deve ser informado(a).");
            }
		}

		return pode;
	}
	
	
	@Transient	
	public boolean isPodeFinalizar(){
	  boolean pode = true;
	  
		if (this.getDataHoraInicio() == null) {
			pode = false;
			FacesUtil.addErrorMessage("O atendimento deve ser inicializado.");
		} else {
			if (this.animal == null ) {
				pode = false;
				FacesUtil.addErrorMessage("O animal deve ser informado informado.");
			} else {
                if (this.veterinario == null){
					pode = false;
					FacesUtil.addErrorMessage("O Dr(a). veterinário(a) deve ser informado(a).");
                } else {

src/main/java/br/spaixaox/controller/PesquisaAtendimentoPacienteBean.java
package br.spaixaox.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.spaixaox.model.AtendimentoPaciente;
import br.spaixaox.model.enums.StatusAtendimentoPaciente;
import br.spaixaox.model.enums.TipoAtendimentoPaciente;
import br.spaixaox.repository.AtendimentoPacienteRepository;
import br.spaixaox.repository.filter.AtendimentoPacienteFilter;

@Controller
@Scope("view")
public class PesquisaAtendimentoPacienteBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Autowired
	private AtendimentoPacienteRepository atendimentoPacienteRepository;
	
	private AtendimentoPacienteFilter filtro;

	private List<AtendimentoPaciente> atendimentosFiltrados;
	
	private String totaisAtendimentos;
	private int totalEmEspera = 0;
	private int totalEmAtendimento = 0;
	private int totalAtendido = 0;
	private int totalCancelado = 0;

	public PesquisaAtendimentoPacienteBean() {
		filtro = new AtendimentoPacienteFilter();
		atendimentosFiltrados = new ArrayList<>();
		//createHorizontalBarModel();
	}
	
	public String getTotaisAtendimentos() {
		return totaisAtendimentos;
	}

	public void pesquisar() {
		atendimentosFiltrados = atendimentoPacienteRepository.filtrados(filtro);
		carregarTotaisAtendimentos();
	}

	/*
	public void pesquisarEmEspera() {
		filtro.setDataAtendimentoDe(new Date());
		filtro.setDataAtendimentoAte(new Date());
		atendimentosFiltrados = atendimentoPacienteRepository.filtradosEmEspera(filtro);
	}*/
	
	public StatusAtendimentoPaciente[] getStatuses() {
		return StatusAtendimentoPaciente.values();
	}

	public TipoAtendimentoPaciente[] getTiposAtendimentos() {
		return TipoAtendimentoPaciente.values();
	}	
	
	public List<AtendimentoPaciente> getAtendimentosFiltrados() {
		return atendimentosFiltrados;
	}

	public AtendimentoPacienteFilter getFiltro() {
		return filtro;
	}
	
	private void carregarTotaisAtendimentos(){

		totalEmEspera = 0;
		totalEmAtendimento = 0;
		totalAtendido = 0;
		totalCancelado = 0;
		
		for (AtendimentoPaciente atendimento : this.atendimentosFiltrados) {

			if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ESPERA.toString())){
				totalEmEspera = totalEmEspera + 1;
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ATENDIMENTO.toString())){
				totalEmAtendimento++;
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.ATENDIDO.toString())){
				totalAtendido++;				
			} else if (atendimento.getStatus().toString().equals(StatusAtendimentoPaciente.CANCELADO.toString())){
				totalCancelado++;
			}
		}
		
		this.totaisAtendimentos = "Em Espera: "+String.valueOf(totalEmEspera)+"     |"+
				                  "Em Atendimento: "+String.valueOf(totalEmAtendimento)+"      |"+
				                  "Atendido(s): "+String.valueOf(totalAtendido)+"     |"+
				                  "Cancelado(s): "+String.valueOf(totalCancelado);

	}

	public int getTotalEmEspera() {
		return totalEmEspera;
	}

	public int getTotalEmAtendimento() {
		return totalEmAtendimento;
	}

	public int getTotalAtendido() {
		return totalAtendido;
	}

	public int getTotalCancelado() {
		return totalCancelado;
	}
	
	/*
	public boolean isUsuarioVeterinario() {
		return seguranca.getTipoGrupoUsuario().toUpperCase().equals("VETERINARIO");
	}*/
	
	/*
	public boolean isUsuarioVeterinarioCirurgiao(){
		if (isUsuarioVeterinario()){
			return seguranca.getVeterinarioUsuario().isCirurgiao();
		} 
		return false;
	}*/	
	/*
	public boolean usuarioPodeAtenderTipoCirurgico(boolean isTipoAtendimentoCirurgico){
		
		if (!isTipoAtendimentoCirurgico){
			return true;
		}else { //é Tipo Atendimento Cirúrgico
			if (!isUsuarioVeterinario()){
				return true;
			} else { //usuário é Veterinário
			    if (isUsuarioVeterinarioCirurgiao()){
					return true;
				} else {
				    return false;			
				}				
			}

		}
	}*/

}

src/main/webapp/atendimentospacientes/AtendimentoPacientes.xhtml
<ui:composition template="/WEB-INF/template/LayoutPrincipal.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="atendimentoPaciente" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente}" />
		<o:viewParam name="animal" value="#{cadastroAtendimentoPacienteBean.atendimentoPaciente.animal}" />		
		<f:event listener="#{cadastroAtendimentoPacienteBean.inicializar}" type="preRenderView" />
	</f:metadata>

    <ui:define name="titulo">Atendimento de Paciente</ui:define>    
    <ui:define name="corpo">
    	<h:form id="frmCadastro">
    	    <p:focus context="frmCadastro"/>
    	   <h1>Atendimento de Paciente</h1>	    	
	    	<p:messages autoUpdate="true" closable="true" />
	    	
	    	<ui:include src="/WEB-INF/template/atendimentospacientes/BotoesAtendimentoPacientes.xhtml" />
	    	
	    	<p:tabView id='id_tabview' style="margin-top: 20px">
	    		<p:tab title="Dados" id='id_tab_dados'>
	    	       <ui:include src="/WEB-INF/template/atendimentospacientes/CorpoAtendimentoPacientes.xhtml"/>		 
	    		</p:tab>
	    		<p:tab title="Histórico" id='id_tab_historico'>
	    			<ui:include src="/WEB-INF/template/atendimentospacientes/HistoricoAtendimentoPacientes.xhtml" />
	    		</p:tab>
	    		<p:tab title="Anexos" id='id_tab_arquivos'>
	    			<ui:include src="/WEB-INF/template/atendimentospacientes/ArquivosAtendimentoPacientes.xhtml" />
	    		</p:tab>
	    	</p:tabView>
	    		    	
	    	<p:tabView style="margin-top: 20px">
	    		<p:tab title="Observação">
	    			<ui:include src="/WEB-INF/template/atendimentospacientes/ObservacaoAtendimentoPacientes.xhtml" />
	    		</p:tab>
	    		<p:tab title="Receituário">
	    	        <ui:include src="/WEB-INF/template/atendimentospacientes/ReceituarioAtendimentoPacientes.xhtml" />   		 
	    		</p:tab>
	    	</p:tabView>
	    	<ui:include src="/WEB-INF/template/atendimentospacientes/BotoesAtendimentoPacientes.xhtml" />
	
    	</h:form>
    </ui:define>
</ui:composition>

src/main/webapp/atendimentospacientes/PesquisaAtendimentoPacientes.xhtml
<ui:composition template="/WEB-INF/template/LayoutPrincipal.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">    
    
    <!-- xmlns:o="http://omnifaces.org/ui" -->

    <ui:define name="titulo">"Pesquisa Atendimentos de Pacientes"</ui:define>
    
    <ui:define name="corpo">
    
    	<h:form id="frmPesquisa">

    	   <h1>Pesquisa Atendimentos de Pacientes</h1>

	    	<p:toolbar style="margin-top: 20px">
	    		<p:toolbarGroup>
	    			<p:commandButton value="Pesquisar" action="#{pesquisaAtendimentoPacienteBean.pesquisar}" update="@form" /> 
	    		</p:toolbarGroup>
	    		<p:toolbarGroup align="right">
	    		</p:toolbarGroup>
	    	</p:toolbar>	    	
	    	
	    	<p:panelGrid columns="4" id="painel" style="width: 100%; margin-top: 20px"
	    			columnClasses="rotulo, campo, rotulo, campo">

      		<p:outputLabel value="Data de Criação De"/>
	    		<h:panelGroup>
	    			<p:calendar size="10" pattern="dd/MM/yyyy"
	    				value="#{pesquisaAtendimentoPacienteBean.filtro.dataAtendimentoDe}" />
	    			a
	    			<p:calendar size="10" pattern="dd/MM/yyyy"
	    				value="#{pesquisaAtendimentoPacienteBean.filtro.dataAtendimentoAte}" />
	    		</h:panelGroup>

	    		<p:outputLabel value="Codigo de Atendimento De" />
	    		<h:panelGroup>
	    		<p:inputText size="10" value="#{pesquisaAtendimentoPacienteBean.filtro.codAtendimentoDe}" />	 
                a
	    		<p:inputText size="10" value="#{pesquisaAtendimentoPacienteBean.filtro.codAtendimentoAte}" />	 
	    		</h:panelGroup>
	    	
	    		<p:outputLabel value="CPF/CNPJ do Proprietário" for="cnpfProprietario" />
	    		<p:inputText id="cnpfProprietario"  value="#{pesquisaAtendimentoPacienteBean.filtro.cpfCnpfProprietario}" size="30" disabled="true"/> 	    		
            
	    		<p:outputLabel value="Nome do Proprietário" for="nomeProprietario" />
	    		<p:inputText id="nomeProprietario"  value="#{pesquisaAtendimentoPacienteBean.filtro.nomeProprietario}" size="30" disabled="true"/> 	    		
 
                <p:outputLabel value="Nome do Animal" for="nomeAnimal" />
	    		<p:inputText size="30" id="nomeAnimal" value="#{pesquisaAtendimentoPacienteBean.filtro.nomeAnimal}"  />	    		

	    		<p:outputLabel value="Código do Animal" for="codAnimal" />
	    		<p:inputText size="30" type="number" id="codAnimal"  value="#{pesquisaAtendimentoPacienteBean.filtro.codigoAnimal}" />
	    		
	    		<p:outputLabel value="Nome do Veterinário" for="nomeveterinario" />
	    		<p:inputText id="nomeveterinario" value="#{pesquisaAtendimentoPacienteBean.filtro.nomeVeterinario}" size="30" />

	    		<p:outputLabel value="Status" />
	    		<p:selectManyCheckbox value="#{pesquisaAtendimentoPacienteBean.filtro.statuses}">
	    			<f:selectItems value="#{pesquisaAtendimentoPacienteBean.statuses}" var="status"
	    				itemValue="#{status}" itemLabel="#{status.descricao}" />
	    		</p:selectManyCheckbox>

	    		<p:outputLabel value="Tipo Atendimento" />
	    		<p:selectManyCheckbox value="#{pesquisaAtendimentoPacienteBean.filtro.tiposAtendimentos}">
	    			<f:selectItems value="#{pesquisaAtendimentoPacienteBean.tiposAtendimentos}" var="tipoAtendimento"
	    				itemValue="#{tipoAtendimento}" itemLabel="#{tipoAtendimento.descricao}" />
	    		</p:selectManyCheckbox>

            </p:panelGrid>
  
           <p:panelGrid columns="1" style="margin-top: 10px">  
          
            <p:panelGrid columns="9" id="painelTotais" style="margin-top: 10px; margin-right: 10px;align=right" 
                styleClass="semBorda" >
            
               <p:outputLabel value="Em Espera:" for="emEspera" styleClass="negrito" />
               <p:outputLabel id="emEspera" value="#{pesquisaAtendimentoPacienteBean.totalEmEspera}"/>
               
               <p:outputLabel value="Em Atendimento:" for="emAtendimento" styleClass="negrito"/>
               <p:outputLabel id="emAtendimento" value="#{pesquisaAtendimentoPacienteBean.totalEmAtendimento}"/>
               
               <p:outputLabel value="Atendido(s):" for="atendidos" styleClass="negrito"/>
               <p:outputLabel id="atendidos" value="#{pesquisaAtendimentoPacienteBean.totalAtendido}"/>
               
               <p:outputLabel value="Cancelado(s):" for="cancelados" styleClass="negrito"/>
               <p:outputLabel id="cancelados" value="#{pesquisaAtendimentoPacienteBean.totalCancelado}"/>                                             
            </p:panelGrid>
           </p:panelGrid>
           
	    	<p:dataTable id="atendimentoTable" value="#{pesquisaAtendimentoPacienteBean.atendimentosFiltrados}" var="atendimento"
		    		 emptyMessage="Nenhum atendimento encontrado." style="margin-top: 10px"
		    		rows="15" paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom">
		    
				<p:column headerText="Data Criação" style="text-align: center; width: 80px">
				   <h:outputFormat  id="data" value="#{atendimento.dataCriacao}">
				      <f:convertDateTime pattern="dd/MM/yyyy" />
				   </h:outputFormat>
				</p:column>

	    		<p:column headerText="Atend." style="text-align: center; width: 30px">
	    			<h:outputText value="#{atendimento.id}"/>
	    		</p:column>

	    		<p:column headerText="Prioritário" style="text-align: center; width: 60px">
	    			<h:outputText value="#{atendimento.nomePrioritario}" />
	    		</p:column>

	    		<p:column headerText="Resumo" style="text-align: center; width: 100px">
	    			<h:outputText value="#{atendimento.resumo}"/>
	    		</p:column>

	    		<p:column headerText="Status" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.status.descricao}"/>
	    		</p:column>	    		

	    		<p:column headerText="Tipo" style="text-align: center; width: 50px">
	    			<h:outputText value="#{atendimento.tipoAtendimentoPaciente.descricao}"/>
	    		</p:column>
	    		
	    		<p:column headerText="Veterinário" style="text-align: center; width: 80px">
	    			<h:outputText value="#{atendimento.veterinario.nome}"/>
	    		</p:column>
	    		
	    		<p:column headerText="Cod. Animal" style="text-align: center; width: 40px">
	    			<h:outputText value="#{atendimento.animal.id}"/>	    			
	    		</p:column>

	    		<p:column headerText="Animal" style="text-align: center; width: 50px">
	    			<h:outputText value="#{atendimento.animal.nome}"/>
	    		</p:column>

	    		<p:column headerText="Proprietário" style="text-align: center; width: 80px">
	    			<h:outputText value="#{atendimento.animal.proprietario.nome}"/>
	    		</p:column>	    		
	    		
	    		<p:column headerText="Espécie" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.animal.especie.nome}"/>
	    		</p:column>

	    		<p:column headerText="Raça" style="text-align: center; width: 70px">
	    			<h:outputText value="#{atendimento.animal.raca.nome}"/>
	    		</p:column>

	    		<p:column headerText="Editar" style="text-align: center; width: 50px">
	    			<p:button icon="ui-icon-pencil" title="Editar Atendimento"
	    			       outcome="/atendimentospacientes/AtendimentoPacientes">
	    				<f:param name="atendimentoPaciente" value="#{atendimento.id}" />
	    			</p:button>
	    		</p:column>

	    		<p:column headerText="Atender" style="text-align: center; width: 50px">
	    			<p:button icon="ui-icon-suitcase" title="Atender"
	    			       outcome="/atendimentospacientes/AtendimentoPacientes">
	    				    <f:param name="atendimentoPaciente" value="#{atendimento.id}" /> 
	    			</p:button>
	    		</p:column>

	    	</p:dataTable>
	    	
    	</h:form>
    </ui:define>
</ui:composition>